#!/bin/bash

set -e

# Support changing environment variable options via docker run -e
env > /etc/ood/config/apps/shell/env

runuser -u ondemand-dex /usr/sbin/ondemand-dex serve /etc/ood/dex/config.yaml &

/opt/rh/httpd24/root/usr/sbin/httpd-scl-wrapper -DFOREGROUND
