# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "rockylinux/8"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder "ood-home", "/home/ood", type: "virtualbox", mount_options: ["uid=1001","gid=1001"]
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.define "ood", primary: true, autostart: true do |ood|
    ood.vm.disk :disk, size: "10GB", primary: true
    ood.vm.network "forwarded_port", guest: 9080, host: 9080
    ood.vm.network "forwarded_port", guest: 5556, host: 5556
    ood.vm.network "private_network", ip: "10.0.0.102"
    ood.vm.provision "shell", inline: <<-SHELL
        printf "\nDisk free space before...\n"
        df -lhT /

        printf "\nResizing / partition live with sgdisk...\n"
        dnf install -y gdisk
        sgdisk -g -e /dev/sda
        sgdisk -d 1 /dev/sda
        sgdisk -N 1 /dev/sda
        partprobe /dev/sda
        xfs_growfs /dev/sda1

        printf "\nDisk free space after...\n"
        df -lhT /
      SHELL
    ood.vm.provision "shell", inline: <<-SHELL
      yum install -y dnf-utils
      dnf config-manager --set-enabled powertools
      dnf module enable -y ruby:3.0 nodejs:14
      yum install -y epel-release lsof sudo
      yum install -y https://yum.osc.edu/ondemand/latest/ondemand-release-web-latest-1-7.noarch.rpm
      yum install -y ondemand ondemand-dex
      #yum -y install xorg-x11-drivers xorg-x11-utils libXt
    SHELL
    ood.vm.provision "shell", path: "../common/ood-setup.sh", args: '9080'
    ood.vm.provision "shell", inline: "systemctl enable httpd"
    ood.vm.provision "shell", inline: "systemctl start httpd"
    ood.vm.provision "shell", inline: "systemctl enable ondemand-dex"
    ood.vm.provision "shell", inline: "systemctl start ondemand-dex"
    ood.vm.provision "shell", inline: "systemctl disable firewalld"
    ood.vm.provision "shell", inline: "systemctl stop firewalld"
    ood.vm.provision "shell", inline: "hostnamectl set-hostname ood"
    ood.vm.provision "file", source: 'hosts', destination: '/tmp/hosts'
    ood.vm.provision "file", source: '../common/example.yml', destination: '/tmp/example.yml'
    ood.vm.provision "shell", inline: "cp -f /tmp/hosts /etc/hosts"
    ood.vm.provision "shell", inline: "cp -f /tmp/example.yml /etc/ood/config/clusters.d/example.yml"
    ood.vm.provision "shell", path: "../common/slurm-setup.sh"
  end
  config.vm.define "head", primary: false, autostart: true do |head|
    head.vm.disk :disk, size: "10GB", primary: true
    head.vm.network "private_network", ip: "10.0.0.103"
    head.vm.provision "shell", inline: <<-SHELL
        printf "\nDisk free space before...\n"
        df -lhT /

        printf "\nResizing / partition live with sgdisk...\n"
        dnf install -y gdisk
        sgdisk -g -e /dev/sda
        sgdisk -d 1 /dev/sda
        sgdisk -N 1 /dev/sda
        partprobe /dev/sda
        xfs_growfs /dev/sda1

        printf "\nDisk free space after...\n"
        df -lhT /
      SHELL
    head.vm.provision "shell", inline: <<-SHELL
      yum install -y dnf-utils
      dnf config-manager --set-enabled powertools
    SHELL
    head.vm.provision "shell", inline: "systemctl disable firewalld"
    head.vm.provision "shell", inline: "systemctl stop firewalld"
    head.vm.provision "shell", path: "../common/head-setup.sh"
    head.vm.provision "shell", inline: "hostnamectl set-hostname head"
    head.vm.provision "file", source: 'hosts', destination: '/tmp/hosts'
    head.vm.provision "shell", inline: "cp -f /tmp/hosts /etc/hosts"
    head.vm.provision "shell", path: "../common/slurm-setup.sh"
    head.vm.provision "shell", inline: "systemctl enable slurmd"
    head.vm.provision "shell", inline: "systemctl start slurmd"
    head.vm.provision "shell", inline: "systemctl enable slurmctld"
    head.vm.provision "shell", inline: "systemctl start slurmctld"
  end
end

