# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# add dev enabling entries to bashrc

source "/opt/rh/rh-ruby24/enable"
source "/opt/rh/rh-ror50/enable"
source "/opt/rh/rh-nodejs6/enable"

