#!/bin/bash -x

set -e

# Support changing environment variable options via docker run -e
ENV_FILE="/etc/ood/config/apps/shell/env"

if [ -f "$ENV_FILE" ]; then
  env > $ENV_FILE
fi

DEFAULT_DEV_DIR="$HOME/ondemand/dev"
OOD_DEV_DIR="/var/www/ood/apps/dev/`whoami`" # $USER isn't set!?

if [ -z $APP_DEV_DIR ]; then
	APP_DEV_DIR=$DEFAULT_DEV_DIR	
fi

sudo su root <<MKDEV
  mkdir -p $OOD_DEV_DIR 
  cd $OOD_DEV_DIR
  ln -s $APP_DEV_DIR gateway
MKDEV

sudo /opt/rh/httpd24/root/usr/sbin/httpd-scl-wrapper -DFOREGROUND
