#!/bin/sh -x

if [ -z $OOD_APP_DEV_DIR ]; then
	OOD_APP_DEV_DIR=$HOME
fi

# load extra stuff if you want
extras_file="$HOME/.local/etc/ood-container.config"
if [ -f "$extras_file" ]; then
	. $extras_file
fi


podman run --rm=true --security-opt label=disable -v $OOD_APP_DEV_DIR:$HOME/ondemand/dev \
  --userns=keep-id ${EXTRA_ARGS} \
  -p 8080:80 ood-$USER:latest
